# Generated by Django 5.2 on 2026-04-28 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodPressureReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolic', models.PositiveSmallIntegerField(help_text='mmHg')),
                ('diastolic', models.PositiveSmallIntegerField(help_text='mmHg')),
                ('pulse', models.PositiveSmallIntegerField(blank=True, help_text='ppm', null=True)),
                ('measured_at', models.DateTimeField(db_index=True)),
                ('time_of_day', models.CharField(blank=True, choices=[('morning', 'Mañana'), ('afternoon', 'Tarde'), ('evening', 'Noche'), ('night', 'Madrugada')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lectura de presión arterial',
                'verbose_name_plural': 'Lecturas de presión arterial',
                'ordering': ['-measured_at'],
                'indexes': [models.Index(fields=['user', 'measured_at'], name='readings_bl_user_id_00c274_idx')],
            },
        ),
    ]
