# Generated by Django 5.2 on 2026-04-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='medical_context',
            field=models.TextField(blank=True, help_text='Edad, peso, actividad física, tipo de trabajo, medicación habitual, etc.', verbose_name='Contexto médico personal'),
        ),
    ]
